### ISSUE TITLE
[Help needed] Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by momics** [scosche/DemoSDK24App#1]
We've just started a project with plans to use the Scosche Rhythm 24 as way to measure HRV accurately. Just stumbled upon the development framework you guys built. Thought I'd give the demo app a spin, but I'm getting the following build error:

> Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.3 compiler

I am really new to developing in Swift and have no clue how to fix this (not even Google could help me here). Perhaps you guys can point me in the right direction? I am on a MacBook pro running XCode 11.3.1 (Catalina).

**Comment by Fox-On-The-Run-NPE** [comment]
![testDemo](https://user-images.githubusercontent.com/52211577/76864237-c5878a00-682e-11ea-82f0-cf07bb8bbffc.jpg)
Hello, I was just alerted about this yesterday. We ran the framework through the 11.3 compiler and updated the cocoaPod ScoscheSDK24. If you run 'pod  upgrade' that should update you to the newest version.

**Comment by momics** [comment]
@Fox-On-The-Run-NPE that's great! I just ran the build again after pod update and the build error is gone. Thank you so much!

Out of the box, the demo still gives me an error 'this class is not key value coding-compliant for the key tableview' but this is not related to the SDK.

**Comment by Fox-On-The-Run-NPE** [comment]
I just added HRV mode and RRInterval to the demo and Framework
