### ISSUE TITLE
[Help please] thread1: signal SIGABRT

### ISSUE THREAD

**Issue by ppcsar** [scosche/DemoSDK24App#3]
We are starting to do our thesis proyect and we need to run the demo to advance and occupy the scoche device in our project. We use Xcode v11.3, an iPhone 6 and a macbook macos catalina 10.15.2. Before running the program we update Swift from 4.2 to 5, We install the pod and update it with pod update. We run the program, but there are errors with bluetooth message protocol and datadecoder, so we update BluetoothMessageProtocol to 2.0.0 and the DataDecoder to 5.0.0 in the pod file and install it again. Those errors stop coming out, but when we run the program, the errors that can be seen in the image appear, likewise the phone screen remains blank. 
![1](https://user-images.githubusercontent.com/67029631/90354397-d8d19800-e00e-11ea-8e69-f149e1e674e1.png)
![2](https://user-images.githubusercontent.com/67029631/90354404-dec77900-e00e-11ea-9f44-c0ecde0db487.png)
![3](https://user-images.githubusercontent.com/67029631/90354451-f3a40c80-e00e-11ea-9b03-7b21918871fc.jpeg)

**Comment by Fox-On-The-Run-NPE** [comment]
The framework has been redesigned in Xcode 12 - Swift 5.2 and now uses no 3rd Party dependencies.

**Comment by ppcsar** [comment]
Thank you very much Steffin.
